{% set name = "sagemaker-jupyterlab-emr-extension" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d36ef57893b91ba26397b7f4e6f9b703828a67f563c1feff3c646c612c3c8ab3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >=3.9
    - jupyterlab >=4
    - sagemaker-jupyterlab-extension-common
    - jsonschema

test:
  imports:
    - sagemaker_jupyterlab_emr_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab EMR extension
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nileshvd
    - c24io
    - zuoyuanh
    - HariniNarayanan
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
    - akrishna1995
